export const CLICKED_HOME ='CLICKED_HOME';
export const CLICKED_ABOUTME ='CLICKED_ABOUTME';
export const CLICKED_RESUME ='CLICKED_RESUME';
export const CLICKED_PORTPOLIO ='CLICKED_PORTPOLIO';
export const CLICKED_CONTACT ='CLICKED_CONTACT';